const { Store, Book, Author, StoreBook } = require('../models');
const asyncHandler = require('../utils/asyncHandler');
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

async function loadLogo(logoValue) {
  if (!logoValue) return null;

  try {
    if (/^https?:\/\//i.test(logoValue)) {
      const response = await fetch(logoValue);
      if (!response.ok) return null;
      return Buffer.from(await response.arrayBuffer());
    }

    const resolvedPath = path.isAbsolute(logoValue)
      ? logoValue
      : path.join(process.cwd(), logoValue);

    await fs.promises.access(resolvedPath, fs.constants.R_OK);
    return await fs.promises.readFile(resolvedPath);
  } catch (err) {
    console.warn('Unable to load logo', err.message);
    return null;
  }
}

// GET /api/store/:id/download-report
// Download store inventory report as PDF
exports.downloadStoreReport = asyncHandler(async (req, res) => {
  const storeId = req.params.id;

  // Validate store exists
  const store = await Store.findByPk(storeId);
  if (!store) {
    return res.status(404).json({
      success: false,
      error: 'Store not found'
    });
  }

  // Get all books in store 
  const storeBooks = await StoreBook.findAll({
    where: { storeId },
    include: [
      {
        model: Book,
        as: 'book',
        include: [{ model: Author, as: 'author' }]
      }
    ],
    order: [['price', 'DESC']]
  });

  if (storeBooks.length === 0) {
    return res.status(404).json({
      success: false,
      error: 'No inventory found for this store'
    });
  }

  // Calculate top 5 priciest books
  const top5Priciest = storeBooks
    .slice(0, 5)
    .map(sb => ({
      name: sb.book.name,
      author: sb.book.author.name,
      price: parseFloat(sb.price),
      copies: sb.copies
    }));

  // Calculate top 5 prolific authors
  const authorStats = {};
  storeBooks.forEach(sb => {
    const authorName = sb.book.author.name;
    if (!authorStats[authorName]) {
      authorStats[authorName] = {
        name: authorName,
        totalBooks: 0,
        totalCopies: 0
      };
    }
    authorStats[authorName].totalBooks++;
    authorStats[authorName].totalCopies += sb.copies;
  });

  const top5Prolific = Object.values(authorStats)
    .sort((a, b) => b.totalCopies - a.totalCopies)
    .slice(0, 5);

  const doc = new PDFDocument({ margin: 50 });
  
  const date = new Date();
  const dateStr = date.toISOString().split('T')[0];
  const filename = `${store.name.replace(/\s+/g, '-')}-Report-${dateStr}.pdf`;
  
  // Set response headers
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  
  // Pipe PDF to response
  doc.pipe(res);

  // Add store logo if available
  const logoBuffer = await loadLogo(store.logo);
  if (logoBuffer) {
    doc.image(logoBuffer, {
      fit: [120, 80],
      align: 'center'
    });
    doc.moveDown(1.5);
  }

  // Header
  doc.fontSize(24).font('Helvetica-Bold').text(store.name, { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(12).font('Helvetica').text(store.address, { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(10).text(`Report Generated: ${date.toLocaleDateString()}`, { align: 'center' });
  doc.moveDown(2);

  doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
  doc.moveDown(1);

  // Top 5 Priciest Books Section
  doc.fontSize(16).font('Helvetica-Bold').text('Top 5 Priciest Books', { underline: true });
  doc.moveDown(1);

  top5Priciest.forEach((book, index) => {
    doc.fontSize(12).font('Helvetica-Bold').text(`${index + 1}. ${book.name}`);
    doc.fontSize(10).font('Helvetica')
      .text(`   Author: ${book.author}`, { continued: true })
      .text(` | Price: ${book.price.toFixed(2)}`, { continued: true })
      .text(` | Copies: ${book.copies}`);
    doc.moveDown(0.5);
  });

  doc.moveDown(1);

  // Divider
  doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
  doc.moveDown(1);

  // Top 5 Prolific Authors Section
  doc.fontSize(16).font('Helvetica-Bold').text('Top 5 Prolific Authors', { underline: true });
  doc.fontSize(10).font('Helvetica-Oblique').text('(Authors with the greatest number of available books)', { italics: true });
  doc.moveDown(1);

  top5Prolific.forEach((author, index) => {
    doc.fontSize(12).font('Helvetica-Bold').text(`${index + 1}. ${author.name}`);
    doc.fontSize(10).font('Helvetica')
      .text(`   Total Books: ${author.totalBooks}`, { continued: true })
      .text(` | Total Copies Available: ${author.totalCopies}`);
    doc.moveDown(0.5);
  });

  doc.moveDown(2);

  // Footer
  doc.fontSize(8).font('Helvetica-Oblique')
    .text(`Generated by Bookstore Inventory System`, 50, doc.page.height - 50, { align: 'center' });

  // Finalize PDF
  doc.end();
});